permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Fairy Cake"
  description: |
    This is a small bakery that produce cakes and bread.Come and buy our products now!
  font_url: "https://fonts.googleapis.com/css?family=Muli:200,300,400,700&display=swap"
  colors:
    background: "--color-secondary-light"
    accent: "--color-primary-dark"
    patterns:
      brand.logos: "--color-primary-light"
    rationales:
      typefaces.primary: |
        Muli was selected because it's a clean and strightforward font. Muli is to be used for all body copy.
      colors.primary: |
        The primary colours because it expresses the theme well.
      colors.secondary: |
        The secondary colour are..
