title: "Navigation"
description: |
  The HTML navigation element represents a section of a page whose purpose is to provide navigation links, either within the current document or to other documents.
patterns:
  navigation_bar:
    title: "Navigation Bar"
    description: |
      A navigation bar is a user interface element within a webpage that contains links to other sections of the website.
